# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty
relative_permalinks: true

# Setup
title:               'HKora''s Blog'
tagline:             'testing...'
description:         'Here are my notes.'
url:                 http://lanyon.getpoole.com
baseurl:             ''
paginate:            5

# About/contact
author:
  name:              'Hou Ke'
  url:               https://twitter.com/mdo
  email:             houke.cn@gmail.com

# Custom vars
version:             6.626
