# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty
relative_permalinks: true

# Setup
title:               'HKora''s Blog'
tagline:             'testing...'
description:         'This is my notes site.'
url:                 http://hkora.github.io/
baseurl:             '/'
paginate:            5

# About/contact
author:
  name:              'Hou Ke'
  github:            hkora
  email:             houke.cn@gmail.com

# Custom vars
version:             6.626
