# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty
relative_permalinks: true

# Setup
title:            hk's notes
tagline:          'testing'
description:      '这家伙很懒,什么都没有留下。'
url:              ''
baseurl:          ''

author:
  name:           'hou ke'
  url:            ''

paginate:         5

# Custom vars
version:          2.1.0

github:           https://github.com/hkora
  repo:           ''
