# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty
relative_permalinks: true

# Setup
title:            testing
tagline:          ''
description:      'hk''s notes'
url:              https://github.com/hkora
baseurl:          /

author:
  name:           'Hou Ke'
  email:          houke.cn@gmail.com
  github:         hkora

paginate:         5

# Custom vars
version:          6.626

github:           https://github.com/hkora
  repo:           https://github.com/hkora/hkora.github.com
