relative_permalinks: true
 
# Setup
title:               hk's notes
tagline:             'Testing'
description:         '这个家伙很懒，什么都没有留下。'
url:                 http://lanyon.getpoole.com
baseurl:             ''
paginate:            5
 
# About/contact
author:
  name:              Hou Ke
  url:               https://github.com/hkora
  email:             houke.cn@gmail.com
 
# Custom vars
version:             1.0.0
