# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty
relative_permalinks: true

# Setup
title:            'hkora-testing'
tagline:          ''
description:      'my''s notes'
url:              'https://github.com/hkora'
baseurl:          '/'

author:
  name:           'Hou Ke'
  email:          houke.cn@gmail.com
  github:         hkora

paginate:         5

# Custom vars
version:          6.626

